#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# displays only
# username
# user id
# Home directory path for the user
while read -r content; do
	echo  "$content" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
