#!/usr/bin/env bash
# Parse an Apache log access file and groups visitors by IP and HTTP status
# 	code, and displays this data
#o	ordered from the greatest to the lowest number of occurrences
awk '{print $1 " " $9}' apache-access.bin | sort | uniq -c |sort -nr
