#!/usr/bin/env bash
# Parse an Apache log access file and group visitors by IP and HTTP status
# code, and display this data.
# Ordered from the greatest to the lowest number of occurrences
awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
