#!/usr/bin/env bash
# Displays the content of the current directory
# where only the part of the name after the first dash is displayed
list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f 2
done
