#!/usr/bin/env bash
# Script that configures an Ubuntu server with these requirements
#	localhost resolves to 127.0.0.2
# 	facebook.com resolves to 8.8.8.8

cp /etc/host ~/hosts.old
echo "127.0.0.2		localhost" > ~/hosts.old
echo "8.8.8.8		facebook.com" >> ~/hosts.old
cp -f ~/hosts.old /etc/hosts
