#!/usr/bin/env bash
# script configures container to fit the following requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# apt-get remove cannot be used

sed -i 's/^user\s\+.*$/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen\s\+80;/c\    listen 8080;\n    listen [::]:8080;' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
