#!/usr/bin/env bash
# Making the fix for task1 short and sweet
apt-get update
apt-get install -y nginx
sed -i 's/^user\s\+.*$/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen\s\+80;/c\    listen 8080;\n    listen [::]:8080;' /etc/nginx/sites-available/default
service nginx restart
